name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Build the Docker image
      run: docker build -t chunwarayut/pig-jungle-back-end:latest .
      
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chunwarayut/pig-jungle-back-end:latest
        
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        private_key: ${{ secrets.SSH_KEY }}
        command: docker pull chunwarayut/pig-jungle-back-end:latest && docker stop pig-jungle-back-end && docker rm pig-jungle-back-end && docker run --name pig-jungle-back-end --restart=always -d -p 6071:3000 chunwarayut/pig-jungle-back-end 
